runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?(google-cloud-sdk/.*)$